version: '3'
services:
  # Jenkins container
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"    # Expose Jenkins UI on port 8080
      - "50000:50000"  # Expose Jenkins agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    networks:
      - bis_network

  # MongoDB container
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./bis_integration:/data/db
      - ./bis_integration:/restaurants

  # Nginx container (2 instances)
  nginx1:
    image: nginx
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html  # Serve HTML files from 'html' folder
    networks:
      - bis_network

  nginx2:
    image: nginx
    ports:
      - "8082:80"
      - "444:443"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - bis_network

networks:
  bis_network:
driver: bridge
volumes:
  jenkins_home: